export const courses = [
  {
    id: 1,
    name: "ওয়েব ডিজাইন",
    xName: "web-design",
    xCategory: "web",
    category: "ওয়েব এন্ড সফটওয়্যার",
    duration: "6 মাস",
    lecture: "৪৮ টি",
    projects: "৮ টি",
    shortDescription:
      "টেকনির্ভর বিশ্বের ট্রেন্ডিং টপিক এখন ডিজিটাল মার্কেটিং। নিত্য প্রয়োজনীয় পণ্য থেকে শুরু করে গাড়ি-বাড়ি পর্যন্ত, যেকোনো কিছু কিনতে বেশিরভাগ মানুষ এখন ইন্টারনেটের দ্বারস্থ হয়। গুগলের তথ্যমতে, প্রায় ৮৭ শতাংশ মানুষ যেকোনো কিছু কেনার আগে আমাজন বা গুগলে সার্চ করে। তাই ব্যবসায় সাফল্য আনতে বা অনলাইন মার্কেটিং শিখতে এনরোল করুন ডিজিটাল মার্কেটিং কোর্সে।",
    longDescription:
      "এক জরিপে দেখা গেছে, একটি আকর্ষণীয় ভিডিও প্রায় ৭৮ শতাংশ পর্যন্ত সেল বাড়ায়। কিন্তু ভালো ভিডিও এর পূর্বশর্ত হল চমৎকার ভিডিও এডিটিং। কারণ একজন দক্ষ এডিটর অসাধারণ এডিটিং এর মাধ্যমে সাধারণ একটা কনসেপ্টকেও দারুণ ভাবে উপস্থাপন করতে পারে। এজন্যই বিশ্বজুড়ে বিভিন্ন কোম্পানিতে প্রফেশনাল ভিডিও এডিটরের চাহিদা বেড়েছে অনেক।  তাই আমাদের কোর্স সাজানো হয়েছে যুগোপযোগী মডিউল আর আধুনিক সফটওয়্যারের সমন্বয়ে। এখানে আপনি সিনেমাটোগ্রাফি আর সাউন্ডট্র্যাক নিয়ে শিখতে পারবেন। ভিডিও পোস্ট প্রোডাকশন আর স্ক্রিনপ্লে নিয়ে কাজ করার জন্য বেশ সহায়ক হবে ভিডিও এডিটিং স্কিল। যদি হতে চান একজন ইউটিউবার, তাহলে তো কথাই নেই! ক্যারিয়ার গড়তে স্কিল ডেভেলাপমেন্টের জন্য এনরোল করতে পারেন Video Editing Course -এ।",
    curriculum: ["html", "css", "javaScript"],
    technologies: ["Adobe Photoshop", "Adobe Illustrator", "Adobe XD", "Figma"],
    whoCanLearn: "",
    workPlace: "",
    jobPosition: "",
  },
  {
    id: 2,
    name: "ওয়েব ডেভেলপমেন্ট",
    xName: "web-development",
    xCategory: "web",
    category: "ওয়েব এন্ড সফটওয়্যার",
    projects: "",
    shortDescription: "",
    longDescription: "",
    curriculum: [],
    technologies: ["Adobe Photoshop", "Adobe Illustrator", "Adobe InDesign"],
    whoCanLearn: "",
    workPlace: "",
    jobPosition: "",
  },
  {
    id: 3,
    name: "মার্ন স্ট্যাক ডেভেলপমেন্ট",
    xName: "mern-stack-development",
    xCategory: "web",
    category: "ওয়েব এন্ড সফটওয়্যার",
    projects: "",
    shortDescription: "",
    longDescription: "",
    curriculum: [],
    technologies: ["Adobe Photoshop", "Adobe Illustrator", "Adobe InDesign"],
    whoCanLearn: "",
    workPlace: "",
    jobPosition: "",
  },
  {
    id: 4,
    name: "অ্যাপ ডেভেলপমেন্ট",
    xName: "app-development",
    xCategory: "web",
    category: "ওয়েব এন্ড সফটওয়্যার",
    projects: "",
    shortDescription: "",
    longDescription: "",
    curriculum: [],
    technologies: ["Adobe Photoshop", "Adobe Illustrator", "Adobe InDesign"],
    whoCanLearn: "",
    workPlace: "",
    jobPosition: "",
  },
  {
    id: 5,
    name: "পাইথন জ্যাঙ্গো",
    xName: "python-django",
    xCategory: "web",
    category: "ওয়েব এন্ড সফটওয়্যার",
    projects: "",
    shortDescription: "",
    longDescription: "",
    curriculum: [],
    technologies: ["Adobe Photoshop", "Adobe Illustrator", "Adobe InDesign"],
    whoCanLearn: "",
    workPlace: "",
    jobPosition: "",
  },
  {
    id: 6,
    name: "পাইথন মেশিন লার্নিং",
    xName: "python-machine-learning",
    xCategory: "web",
    category: "ওয়েব এন্ড সফটওয়্যার",
    projects: "",
    shortDescription: "",
    longDescription: "",
    curriculum: [],
    technologies: ["Adobe Photoshop", "Adobe Illustrator", "Adobe InDesign"],
    whoCanLearn: "",
    workPlace: "",
    jobPosition: "",
  },
  {
    id: 7,
    name: "প্রফেশনাল গ্রাফিক্স ডিজাইন",
    xName: "professional-graphics-design",
    xCategory: "graphics",
    category: "গ্রাফিক্স ডিজাইন",
    projects: "",
    shortDescription: "",
    longDescription: "",
    curriculum: [],
    technologies: ["Adobe Photoshop", "Adobe Illustrator", "Adobe InDesign"],
    whoCanLearn: "",
    workPlace: "",
    jobPosition: "",
  },
];

export const pages = [
  "হোম",
  "আমাদের সম্পর্কে",
  "সেবাসমুহ",
  "কোর্সসমূহ",
  "ক্যারিয়ার",
  "যোগাযোগ",
];
